behaviors:
  cooking:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 8192
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
        learning_rate: 3.0e-4
    keep_checkpoints: 5
    max_steps: 20000000
    time_horizon: 512
    summary_freq: 20000
    threaded: true
environment_parameters:
  lessonNum:
    curriculum:
      - name: GetBeefedOn # Interact with beef
        completion_criteria:
          measure: reward
          behavior: cooking
          signal_smoothing: true
          min_lesson_length: 1000
          threshold: 1.0
        value: 0.0
      - name: CookThatMeat # Put beef in oven
        completion_criteria:
          measure: reward
          behavior: cooking
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.0
        value: 1.0
      - name: SlapUrBuns # Grab plate, buns, and cooked burger
        completion_criteria:
          measure: reward
          behavior: cooking
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value: 2.0
      - name: TheFullSpiel # Add all chopped ingredients to burger
        completion_criteria:
          measure: reward
          behavior: cooking
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value: 3.0
      - name: OrderUp # Serve finished burger to customer
        completion_criteria:
          measure: reward
          behavior: cooking
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value: 4.0
      - name: PickyEaters # Give customer burger based on order (orders should change here)
        completion_criteria:
          measure: reward
          behavior: cooking
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.8
        value: 5.0
      - name: AmericanPortionSize # Customer makes multiple orders
        value: 6.0

